version: '3.0'

services:
  configmanager:
    build:
      context: .
    container_name: 'configurationmanager-container'
    ports:
      - 8081:8081
    environment:
      - CUSTOM_APP_NAME=Einfache Wetterwarnungen auf Gemeindeebene
      - DATASPACE_COMMUNICATION_SSL=true
